volumes:
  writer:
  reader:

networks:
  coupon_dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  mysql_writer:
    user: root
    build:
      context: ./writer
      dockerfile: Dockerfile
    ports:
      - 33306:3306
    networks:
      coupon_dock_net:
        ipv4_address: 172.20.0.10
    volumes:
      - writer:/var/lib/mysql
    container_name: mysql_writer
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon
      LANG: C.UTF-8
      TZ: Asia/Seoul

  mysql_reader:
    user: root
    build:
      context: ./reader
      dockerfile: Dockerfile
    ports:
      - 33307:3306
    networks:
      coupon_dock_net:
        ipv4_address: 172.20.0.11
    volumes:
      - reader:/var/lib/mysql
    container_name: mysql_reader
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon
      LANG: C.UTF-8
      TZ: Asia/Seoul
    depends_on:
      - mysql_writer

  redis:
    image: redis:7.0.12
    container_name: redis
    restart: unless-stopped
    ports:
      - "36379:6379"
    networks:
      coupon_dock_net:
        ipv4_address: 172.20.0.20
